name: schedule_share_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2

  # Calendar UI & Helpers
  table_calendar: ^3.1.2
  linked_scroll_controller: ^0.2.0 # スクロール同期に必須
  collection: ^1.18.0             # データ処理に必須
  intl: ^0.20.2                   # 日付フォーマットに必須

  # Default
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true