// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjHtG8a15c5AlExcLmYDo4u_u8YwjlyL8',
    appId: '1:431625859855:web:94dc8d228074b23b8cc47a',
    messagingSenderId: '431625859855',
    projectId: 'schedule-share-app-bbb37',
    authDomain: 'schedule-share-app-bbb37.firebaseapp.com',
    storageBucket: 'schedule-share-app-bbb37.firebasestorage.app',
    measurementId: 'G-PQDJ87NP86',
  );

  // 本番環境では環境変数から取得するか、別の安全な方法で管理してください

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACCI_2bTMLXD27mjihCsVP6TTXdng-2Dw',
    appId: '1:431625859855:android:12c3b1815284de718cc47a',
    messagingSenderId: '431625859855',
    projectId: 'schedule-share-app-bbb37',
    storageBucket: 'schedule-share-app-bbb37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp7_NzXnBHsWMaKnXvy3EaLxcu-Eis1GE',
    appId: '1:431625859855:ios:a3720571c494d4b68cc47a',
    messagingSenderId: '431625859855',
    projectId: 'schedule-share-app-bbb37',
    storageBucket: 'schedule-share-app-bbb37.firebasestorage.app',
    iosBundleId: 'com.example.scheduleShareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp7_NzXnBHsWMaKnXvy3EaLxcu-Eis1GE',
    appId: '1:431625859855:ios:a3720571c494d4b68cc47a',
    messagingSenderId: '431625859855',
    projectId: 'schedule-share-app-bbb37',
    storageBucket: 'schedule-share-app-bbb37.firebasestorage.app',
    iosBundleId: 'com.example.scheduleShareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjHtG8a15c5AlExcLmYDo4u_u8YwjlyL8',
    appId: '1:431625859855:web:a7a3fe2220e0fe0e8cc47a',
    messagingSenderId: '431625859855',
    projectId: 'schedule-share-app-bbb37',
    authDomain: 'schedule-share-app-bbb37.firebaseapp.com',
    storageBucket: 'schedule-share-app-bbb37.firebasestorage.app',
    measurementId: 'G-T3JC00R1X9',
  );

}